# Generated by Django 4.0.3 on 2022-04-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_page_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='base.page'),
        ),
    ]
