# Generated by Django 4.0.3 on 2022-04-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_section_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
